// GENERATED by scripts/cryptapi-coins.ts from https://api.cryptapi.io/info/ on 2026-10-08.
// Do not edit by hand: run `node scripts/cryptapi-coins.ts --write` and commit the result.
//
// The coins a SPACE can be funded with: those CryptAPI forwards on a network the service
// has a receiving wallet for (every EVM network, Solana, Bitcoin, Tron). 98 coins.
// cheap: feeUsd, CryptAPI's estimate of the network fee to forward a deposit, is below $0.50.

/** Which receiving wallet a coin is forwarded to. Every EVM network shares one. */
export type CoinFamily = "evm" | "solana" | "btc" | "tron";

export const COIN_FAMILIES: readonly CoinFamily[] = ["evm", "solana", "btc", "tron"];

export interface Coin {
  /** As CryptAPI's paths spell it: `btc`, `base/usdc`, `trc20/usdt`. */
  readonly ticker: string;
  /** As a callback's `coin` field spells it: the ticker with `_` for `/`. CryptAPI documents
   * this form for erc20, bep20, trc20 and polygon tokens; the rest follow the same rule. */
  readonly callbackCoin: string;
  /** The coin's own ticker, upper case: `USDC`. */
  readonly symbol: string;
  /** CryptAPI's name for the coin. */
  readonly name: string;
  /** The network it moves on, as a person reads it. */
  readonly network: string;
  readonly family: CoinFamily;
  /** native: the coin that pays the network's fees; token: any other coin on it. */
  readonly kind: "native" | "token";
  /** The smallest deposit CryptAPI forwards, in the coin's units, as a decimal. */
  readonly minimum: string;
  /** CryptAPI's estimate of the network fee to forward one deposit, in dollars, to the cent,
   * when the table was made: /info/'s network_fee_estimation, in the coin its network's
   * fees are paid in, times that coin's price. Read by the generator alone. */
  readonly feeUsd: string;
  /** feeUsd is below $0.50. */
  readonly cheap: boolean;
  /** A USD stablecoin, credited one for one. */
  readonly stable: boolean;
}

/** The UTC day the minimums were read from CryptAPI. */
export const COINS_AS_OF = "2026-10-08";

export const COINS: readonly Coin[] = [
  { ticker: "arbitrum/arb", callbackCoin: "arbitrum_arb", symbol: "ARB", name: "Arbitrum", network: "Arbitrum", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "arbitrum/dai", callbackCoin: "arbitrum_dai", symbol: "DAI", name: "Dai Token", network: "Arbitrum", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "arbitrum/eth", callbackCoin: "arbitrum_eth", symbol: "ETH", name: "Ethereum", network: "Arbitrum", family: "evm", kind: "native", minimum: "0.0001", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "arbitrum/link", callbackCoin: "arbitrum_link", symbol: "LINK", name: "ChainLink Token", network: "Arbitrum", family: "evm", kind: "token", minimum: "0.05", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "arbitrum/pepe", callbackCoin: "arbitrum_pepe", symbol: "PEPE", name: "PEPE Token", network: "Arbitrum", family: "evm", kind: "token", minimum: "100000", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "arbitrum/pyusd", callbackCoin: "arbitrum_pyusd", symbol: "PYUSD", name: "PayPal USD", network: "Arbitrum", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "arbitrum/usdc", callbackCoin: "arbitrum_usdc", symbol: "USDC", name: "USD Coin (Native)", network: "Arbitrum", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "arbitrum/usdc.e", callbackCoin: "arbitrum_usdc.e", symbol: "USDC.E", name: "USD Coin (Bridged)", network: "Arbitrum", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "arbitrum/usdt0", callbackCoin: "arbitrum_usdt0", symbol: "USDT0", name: "USD₮0", network: "Arbitrum", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "avax-c/avax", callbackCoin: "avax-c_avax", symbol: "AVAX", name: "AVAX", network: "Avalanche C-Chain", family: "evm", kind: "native", minimum: "0.01", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "avax-c/usdc", callbackCoin: "avax-c_usdc", symbol: "USDC", name: "USD Coin (Native)", network: "Avalanche C-Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "avax-c/usdc.e", callbackCoin: "avax-c_usdc.e", symbol: "USDC.E", name: "USD Coin (Bridged)", network: "Avalanche C-Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "avax-c/usdt", callbackCoin: "avax-c_usdt", symbol: "USDT", name: "USDT", network: "Avalanche C-Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: true },
  { ticker: "avax-c/wavax", callbackCoin: "avax-c_wavax", symbol: "WAVAX", name: "Wrapped AVAX", network: "Avalanche C-Chain", family: "evm", kind: "token", minimum: "0.01", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "avax-c/weth.e", callbackCoin: "avax-c_weth.e", symbol: "WETH.E", name: "Wrapped Ether", network: "Avalanche C-Chain", family: "evm", kind: "token", minimum: "0.001", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "base/cbbtc", callbackCoin: "base_cbbtc", symbol: "CBBTC", name: "Coinbase Wrapped BTC", network: "Base", family: "evm", kind: "token", minimum: "0.00003", feeUsd: "0.75", cheap: false, stable: false },
  { ticker: "base/cbltc", callbackCoin: "base_cbltc", symbol: "CBLTC", name: "Coinbase Wrapped LTC", network: "Base", family: "evm", kind: "token", minimum: "0.05", feeUsd: "0.76", cheap: false, stable: false },
  { ticker: "base/dai", callbackCoin: "base_dai", symbol: "DAI", name: "Dai Token", network: "Base", family: "evm", kind: "token", minimum: "3", feeUsd: "0.76", cheap: false, stable: true },
  { ticker: "base/eth", callbackCoin: "base_eth", symbol: "ETH", name: "Ethereum", network: "Base", family: "evm", kind: "native", minimum: "0.0003", feeUsd: "0.22", cheap: true, stable: false },
  { ticker: "base/usdc", callbackCoin: "base_usdc", symbol: "USDC", name: "USD Coin", network: "Base", family: "evm", kind: "token", minimum: "3", feeUsd: "0.76", cheap: false, stable: true },
  { ticker: "base/usdt", callbackCoin: "base_usdt", symbol: "USDT", name: "USDT", network: "Base", family: "evm", kind: "token", minimum: "3", feeUsd: "0.75", cheap: false, stable: true },
  { ticker: "bep20/1inch", callbackCoin: "bep20_1inch", symbol: "1INCH", name: "1INCH Token", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/ada", callbackCoin: "bep20_ada", symbol: "ADA", name: "Cardano", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/bnb", callbackCoin: "bep20_bnb", symbol: "BNB", name: "BNB", network: "BNB Chain", family: "evm", kind: "native", minimum: "0.001", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "bep20/btcb", callbackCoin: "bep20_btcb", symbol: "BTCB", name: "BTCB", network: "BNB Chain", family: "evm", kind: "token", minimum: "0.00008", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "bep20/cake", callbackCoin: "bep20_cake", symbol: "CAKE", name: "PancakeSwap", network: "BNB Chain", family: "evm", kind: "token", minimum: "0.1", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "bep20/dai", callbackCoin: "bep20_dai", symbol: "DAI", name: "Dai Token", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: true },
  { ticker: "bep20/doge", callbackCoin: "bep20_doge", symbol: "DOGE", name: "Dogecoin", network: "BNB Chain", family: "evm", kind: "token", minimum: "10", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/eth", callbackCoin: "bep20_eth", symbol: "ETH", name: "ETH", network: "BNB Chain", family: "evm", kind: "token", minimum: "0.00075", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/ltc", callbackCoin: "bep20_ltc", symbol: "LTC", name: "LTC", network: "BNB Chain", family: "evm", kind: "token", minimum: "0.002", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/phpt", callbackCoin: "bep20_phpt", symbol: "PHPT", name: "PHPt", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "bep20/shib", callbackCoin: "bep20_shib", symbol: "SHIB", name: "SHIBA INU", network: "BNB Chain", family: "evm", kind: "token", minimum: "40000", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/trx", callbackCoin: "bep20_trx", symbol: "TRX", name: "TRX", network: "BNB Chain", family: "evm", kind: "token", minimum: "5", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/usd1", callbackCoin: "bep20_usd1", symbol: "USD1", name: "World Liberty Financial USD", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bep20/usdc", callbackCoin: "bep20_usdc", symbol: "USDC", name: "USDC", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "bep20/usdt", callbackCoin: "bep20_usdt", symbol: "USDT", name: "USDT", network: "BNB Chain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.02", cheap: true, stable: true },
  { ticker: "bep20/xrp", callbackCoin: "bep20_xrp", symbol: "XRP", name: "XRP", network: "BNB Chain", family: "evm", kind: "token", minimum: "2", feeUsd: "0.02", cheap: true, stable: false },
  { ticker: "bera/bera", callbackCoin: "bera_bera", symbol: "BERA", name: "Bera", network: "Berachain", family: "evm", kind: "native", minimum: "3", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "bera/usdt0", callbackCoin: "bera_usdt0", symbol: "USDT0", name: "USD₮0", network: "Berachain", family: "evm", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "bera/wbtc", callbackCoin: "bera_wbtc", symbol: "WBTC", name: "Wrapped BTC", network: "Berachain", family: "evm", kind: "token", minimum: "0.00002", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "bera/weth", callbackCoin: "bera_weth", symbol: "WETH", name: "Wrapped Ether", network: "Berachain", family: "evm", kind: "token", minimum: "0.0006", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "btc", callbackCoin: "btc", symbol: "BTC", name: "Bitcoin", network: "Bitcoin", family: "btc", kind: "native", minimum: "0.00008", feeUsd: "0.18", cheap: true, stable: false },
  { ticker: "erc20/1inch", callbackCoin: "erc20_1inch", symbol: "1INCH", name: "1INCH Token", network: "Ethereum", family: "evm", kind: "token", minimum: "75", feeUsd: "0.84", cheap: false, stable: false },
  { ticker: "erc20/arb", callbackCoin: "erc20_arb", symbol: "ARB", name: "Arbitrum", network: "Ethereum", family: "evm", kind: "token", minimum: "15", feeUsd: "0.63", cheap: false, stable: false },
  { ticker: "erc20/bnb", callbackCoin: "erc20_bnb", symbol: "BNB", name: "Binance Coin", network: "Ethereum", family: "evm", kind: "token", minimum: "0.09", feeUsd: "0.85", cheap: false, stable: false },
  { ticker: "erc20/cbbtc", callbackCoin: "erc20_cbbtc", symbol: "CBBTC", name: "Coinbase Wrapped BTC", network: "Ethereum", family: "evm", kind: "token", minimum: "0.00009", feeUsd: "0.85", cheap: false, stable: false },
  { ticker: "erc20/dai", callbackCoin: "erc20_dai", symbol: "DAI", name: "Dai Token", network: "Ethereum", family: "evm", kind: "token", minimum: "15", feeUsd: "0.84", cheap: false, stable: true },
  { ticker: "erc20/link", callbackCoin: "erc20_link", symbol: "LINK", name: "ChainLink Token", network: "Ethereum", family: "evm", kind: "token", minimum: "0.65", feeUsd: "0.83", cheap: false, stable: false },
  { ticker: "erc20/musd", callbackCoin: "erc20_musd", symbol: "MUSD", name: "MetaMask USD", network: "Ethereum", family: "evm", kind: "token", minimum: "5", feeUsd: "0.84", cheap: false, stable: false },
  { ticker: "erc20/ondo", callbackCoin: "erc20_ondo", symbol: "ONDO", name: "Ondo", network: "Ethereum", family: "evm", kind: "token", minimum: "10", feeUsd: "0.85", cheap: false, stable: false },
  { ticker: "erc20/pepe", callbackCoin: "erc20_pepe", symbol: "PEPE", name: "PEPE Token", network: "Ethereum", family: "evm", kind: "token", minimum: "1000000", feeUsd: "0.65", cheap: false, stable: false },
  { ticker: "erc20/pol", callbackCoin: "erc20_pol", symbol: "POL", name: "POL", network: "Ethereum", family: "evm", kind: "token", minimum: "25", feeUsd: "0.65", cheap: false, stable: false },
  { ticker: "erc20/pyusd", callbackCoin: "erc20_pyusd", symbol: "PYUSD", name: "PayPal USD", network: "Ethereum", family: "evm", kind: "token", minimum: "2", feeUsd: "0.87", cheap: false, stable: true },
  { ticker: "erc20/shib", callbackCoin: "erc20_shib", symbol: "SHIB", name: "SHIBA INU", network: "Ethereum", family: "evm", kind: "token", minimum: "1000000", feeUsd: "0.83", cheap: false, stable: false },
  { ticker: "erc20/trx", callbackCoin: "erc20_trx", symbol: "TRX", name: "TRX", network: "Ethereum", family: "evm", kind: "token", minimum: "15", feeUsd: "0.65", cheap: false, stable: false },
  { ticker: "erc20/usd1", callbackCoin: "erc20_usd1", symbol: "USD1", name: "World Liberty Financial USD", network: "Ethereum", family: "evm", kind: "token", minimum: "5", feeUsd: "0.85", cheap: false, stable: false },
  { ticker: "erc20/usdc", callbackCoin: "erc20_usdc", symbol: "USDC", name: "USD Coin", network: "Ethereum", family: "evm", kind: "token", minimum: "2", feeUsd: "0.83", cheap: false, stable: true },
  { ticker: "erc20/usdt", callbackCoin: "erc20_usdt", symbol: "USDT", name: "USDT", network: "Ethereum", family: "evm", kind: "token", minimum: "2", feeUsd: "0.84", cheap: false, stable: true },
  { ticker: "erc20/wxrp", callbackCoin: "erc20_wxrp", symbol: "WXRP", name: "Wrapped XRP", network: "Ethereum", family: "evm", kind: "token", minimum: "6", feeUsd: "0.84", cheap: false, stable: false },
  { ticker: "eth", callbackCoin: "eth", symbol: "ETH", name: "Ethereum", network: "Ethereum", family: "evm", kind: "native", minimum: "0.0015", feeUsd: "0.23", cheap: true, stable: false },
  { ticker: "linea/eth", callbackCoin: "linea_eth", symbol: "ETH", name: "ETH", network: "Linea", family: "evm", kind: "native", minimum: "0.0001", feeUsd: "0.13", cheap: true, stable: false },
  { ticker: "linea/musd", callbackCoin: "linea_musd", symbol: "MUSD", name: "MetaMask USD", network: "Linea", family: "evm", kind: "token", minimum: "1", feeUsd: "0.44", cheap: true, stable: false },
  { ticker: "linea/usdc", callbackCoin: "linea_usdc", symbol: "USDC", name: "USDC", network: "Linea", family: "evm", kind: "token", minimum: "1", feeUsd: "0.42", cheap: true, stable: true },
  { ticker: "linea/usdt", callbackCoin: "linea_usdt", symbol: "USDT", name: "USDT", network: "Linea", family: "evm", kind: "token", minimum: "1", feeUsd: "0.44", cheap: true, stable: true },
  { ticker: "monad/mon", callbackCoin: "monad_mon", symbol: "MON", name: "Monad", network: "Monad", family: "evm", kind: "native", minimum: "10", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "monad/usdc", callbackCoin: "monad_usdc", symbol: "USDC", name: "USDC", network: "Monad", family: "evm", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "monad/usdt0", callbackCoin: "monad_usdt0", symbol: "USDT0", name: "USDT0", network: "Monad", family: "evm", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "optimism/dai", callbackCoin: "optimism_dai", symbol: "DAI", name: "Dai Token", network: "Optimism", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "optimism/eth", callbackCoin: "optimism_eth", symbol: "ETH", name: "Ethereum", network: "Optimism", family: "evm", kind: "native", minimum: "0.0001", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "optimism/link", callbackCoin: "optimism_link", symbol: "LINK", name: "ChainLink Token", network: "Optimism", family: "evm", kind: "token", minimum: "0.05", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "optimism/op", callbackCoin: "optimism_op", symbol: "OP", name: "Optimism", network: "Optimism", family: "evm", kind: "token", minimum: "0.3", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "optimism/usdc", callbackCoin: "optimism_usdc", symbol: "USDC", name: "USD Coin (Native)", network: "Optimism", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "optimism/usdc.e", callbackCoin: "optimism_usdc.e", symbol: "USDC.E", name: "USD Coin (Bridged)", network: "Optimism", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "optimism/usdt", callbackCoin: "optimism_usdt", symbol: "USDT", name: "USDT", network: "Optimism", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "optimism/usdt0", callbackCoin: "optimism_usdt0", symbol: "USDT0", name: "USD₮0", network: "Optimism", family: "evm", kind: "token", minimum: "1", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "polygon/avax", callbackCoin: "polygon_avax", symbol: "AVAX", name: "Avalanche Token", network: "Polygon", family: "evm", kind: "token", minimum: "0.04", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "polygon/pol", callbackCoin: "polygon_pol", symbol: "POL", name: "POL", network: "Polygon", family: "evm", kind: "native", minimum: "0.5", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "polygon/usdc", callbackCoin: "polygon_usdc", symbol: "USDC", name: "USD Coin (Native)", network: "Polygon", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "polygon/usdc.e", callbackCoin: "polygon_usdc.e", symbol: "USDC.E", name: "USD Coin (Bridged)", network: "Polygon", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "polygon/usdt", callbackCoin: "polygon_usdt", symbol: "USDT", name: "USDT", network: "Polygon", family: "evm", kind: "token", minimum: "0.5", feeUsd: "0.01", cheap: true, stable: true },
  { ticker: "polygon/weth", callbackCoin: "polygon_weth", symbol: "WETH", name: "Wrapped Ether", network: "Polygon", family: "evm", kind: "token", minimum: "0.0005", feeUsd: "0.01", cheap: true, stable: false },
  { ticker: "sol/cbbtc", callbackCoin: "sol_cbbtc", symbol: "CBBTC", name: "Coinbase Wrapped BTC", network: "Solana", family: "solana", kind: "token", minimum: "0.000009", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/eurc", callbackCoin: "sol_eurc", symbol: "EURC", name: "EURC", network: "Solana", family: "solana", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/hnt", callbackCoin: "sol_hnt", symbol: "HNT", name: "Helium", network: "Solana", family: "solana", kind: "token", minimum: "2.5", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/pyusd", callbackCoin: "sol_pyusd", symbol: "PYUSD", name: "PayPal USD", network: "Solana", family: "solana", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "sol/sol", callbackCoin: "sol_sol", symbol: "SOL", name: "Solana", network: "Solana", family: "solana", kind: "native", minimum: "0.004", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/trump", callbackCoin: "sol_trump", symbol: "TRUMP", name: "Trump", network: "Solana", family: "solana", kind: "token", minimum: "0.05", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/usdc", callbackCoin: "sol_usdc", symbol: "USDC", name: "USDC", network: "Solana", family: "solana", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "sol/usdt", callbackCoin: "sol_usdt", symbol: "USDT", name: "USDT", network: "Solana", family: "solana", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: true },
  { ticker: "sol/wbtc", callbackCoin: "sol_wbtc", symbol: "WBTC", name: "Wrapped BTC", network: "Solana", family: "solana", kind: "token", minimum: "0.000009", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/weth", callbackCoin: "sol_weth", symbol: "WETH", name: "Wrapped Ether (Wormhole)", network: "Solana", family: "solana", kind: "token", minimum: "0.003", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "sol/wusdt", callbackCoin: "sol_wusdt", symbol: "WUSDT", name: "Wormhole USDT", network: "Solana", family: "solana", kind: "token", minimum: "1", feeUsd: "0.00", cheap: true, stable: false },
  { ticker: "trc20/btc", callbackCoin: "trc20_btc", symbol: "BTC", name: "BTC", network: "Tron", family: "tron", kind: "token", minimum: "0.00008", feeUsd: "2.01", cheap: false, stable: false },
  { ticker: "trc20/inrt", callbackCoin: "trc20_inrt", symbol: "INRT", name: "INRT", network: "Tron", family: "tron", kind: "token", minimum: "1", feeUsd: "2.01", cheap: false, stable: false },
  { ticker: "trc20/tusd", callbackCoin: "trc20_tusd", symbol: "TUSD", name: "TrueUSD", network: "Tron", family: "tron", kind: "token", minimum: "5", feeUsd: "2.01", cheap: false, stable: false },
  { ticker: "trc20/usdd", callbackCoin: "trc20_usdd", symbol: "USDD", name: "Decentralized USD", network: "Tron", family: "tron", kind: "token", minimum: "5", feeUsd: "2.01", cheap: false, stable: false },
  { ticker: "trc20/usdt", callbackCoin: "trc20_usdt", symbol: "USDT", name: "USDT", network: "Tron", family: "tron", kind: "token", minimum: "10", feeUsd: "4.33", cheap: false, stable: true },
  { ticker: "trx", callbackCoin: "trx", symbol: "TRX", name: "TRX", network: "Tron", family: "tron", kind: "native", minimum: "10", feeUsd: "1.01", cheap: false, stable: false },
];

const BY_TICKER = new Map(COINS.map((c) => [c.ticker, c]));
const BY_CALLBACK_COIN = new Map(COINS.map((c) => [c.callbackCoin, c]));

/** The coin CryptAPI's path names, or undefined when the service does not offer it. */
export function coinByTicker(ticker: string): Coin | undefined {
  return BY_TICKER.get(ticker);
}

/** The coin a callback's `coin` field names, or undefined when the service does not offer it. */
export function coinByCallbackCoin(coin: string): Coin | undefined {
  return BY_CALLBACK_COIN.get(coin);
}
